### ISSUE TITLE
Getting error while using the library in Xcode 9

### ISSUE THREAD

**Issue by nikhilpandey4** [T-Pham/UITextField-Navigation#10]
Hi,
While using the library in Xcode Version 9.0 beta 6 (9M214v), I am getting the error that modules Module compiled with Swift 3.1 cannot be imported in Swift 3.2/ Swift 4.0. Now new iPhone launch is just one week ahead on 12th September and even the Xcode 9 GM seed will be launched on the same day. Requested to update the project to at least Swift 3.2.

**Comment by nikhilpandey4** [comment]
Hi,
Tried to run in Xcode 9 beta 6 and was able to run but getting following warning 
The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the  target.

**Comment by T-Pham** [comment]
@nikhilpandey4 this is fixed with the latest release version 4.0.0. Thanks for reporting.
