### ISSUE TITLE
iOS 11 - tint color isn't applied to NavigationBar

### ISSUE THREAD

**Issue by VitaliyR** [T-Pham/UITextField-Navigation#12]
Hello.

On iOS 11 tint color not applied to NavigationBar.

```swift
NavigationFieldToolbarButtonItem.appearance().tintColor = UIColor.white
```

Is works for iOS 10 but isn't for iOS 11

**Comment by T-Pham** [comment]
Hey @VitaliyR, thanks for reporting this issue.
iOS 11 changes the way it handles UIBarButtonItem in the view hierarchy so setting `tintColor` on `UIBarButtonItem`'s appearance does not work anymore. We now have to set `tintColor` on the appearance of `UIButton` contained in `UIToolbar` instead.
I have updated the Example app as well as the README to reflect that.

Reference: https://stackoverflow.com/questions/45893605/changing-the-tint-colour-of-elements-in-uinavigationbar-ios-11

**Comment by VitaliyR** [comment]
@T-Pham indeed, missed this one, thank you. And 👍  for updating readme
