### ISSUE TITLE
previousNavigationField is get-only?

### ISSUE THREAD

**Issue by aabosh** [T-Pham/UITextField-Navigation#14]
Hi,

I just updated my app to Swift 4 and in the process, updated to the latest build of UITextField-Navigation. While migrating, I noticed that I can longer set the `previousNavigationField` property. I used this previously to help set the order of the next and previous buttons, but now I'm confused as what to do. Is there a better way to set the previous field? I'm quite lost and would appreciate any help.

Thanks,
Andrew

**Comment by T-Pham** [comment]
Hi Andrew,
The `previousNavigationField` property has always been get-only. It’s the `nextNavigationField` property that is get- and set-able.
When you set B as `nextNavigationField` of A, the lib will automatically set A as `previousNavigationField` of B.
