### ISSUE TITLE
Globally customize NavigationFieldToolbar 

### ISSUE THREAD

**Issue by garrialmighty** [T-Pham/UITextField-Navigation#15]
First of all thank you very much for creating this library.
I have used it in multiple projects and it has saved me a ton of customization code!

My issue is that is there currently an easy way of globally modifying the `previousButton`, `nextButton`, and `doneButton` titles without subclassing?
The current workaround I did is that I unlocked and modified the `NavigationFieldToolbar.swift` file and manually replaced the string literals there.

**Comment by T-Pham** [comment]
Hi @garrialmighty, thanks for raising this issue.
The new version 4.0.2 introduces a global `Config` which can be used to set button titles globally like this:

```swift
UITextField_Navigation.Config.previousButtonTitle = "Previous"
UITextField_Navigation.Config.nextButtonTitle = "Next"
UITextField_Navigation.Config.doneButtonTitle = "Done"
```

**Comment by T-Pham** [comment]
Do give me feedback if you think there is a better way to do this kind of global config.
