### ISSUE TITLE
Warning appears when we upload Xcode to 9.3 with Swift 4.1

### ISSUE THREAD

**Issue by nikhilpandey4** [T-Pham/UITextField-Navigation#16]
Hi while upgrading to Xcode 9.3 with Swift 4.1 following warning appears

**'weak' should not be applied to a property declaration in a protocol and will be disallowed in future versions**

And then Xcode 9.3 takes to following lines of code 

`protocol NavigationFieldInternal: NavigationField, NavigationFieldToolbarDelegate {

    var internal_delegate: AnyObject? { get }
    **weak var internal_nextNavigationField: NavigationField? { get set }
    weak var internal_previousNavigationField: NavigationField? { get set }**

    func internal_applyInputAccessoryView()

    func storeNavigationField(_ navigationField: NavigationField?, key: UnsafeRawPointer)
    func retrieveNavigationField(key: UnsafeRawPointer) -> NavigationField?
}`

**Comment by T-Pham** [comment]
Thanks for reporting @nikhilpandey4. Issue fixed in version 4.0.3.
