### ISSUE TITLE
Upgrade to Swift 4.2 and Xcode 10

### ISSUE THREAD

**Issue by nikhilpandey4** [T-Pham/UITextField-Navigation#19]
Hi,
Can you just update the project for Swift 4.2 and Xcode 10.0.

**Comment by T-Pham** [comment]
@nikhilpandey4 if you are using the lib as a CocoaPod for your project, there should be nothing to update.
If you are referring to updating Swift and Xcode for this library project itself, checkout my latest commit on `master` branch 👍

**Comment by nikhilpandey4** [comment]
Dear Pham,
Thanks for your efforts.
Regards,
Nikhil
