### ISSUE TITLE
issue with textfield if it is under keyboard or toolbar 

### ISSUE THREAD

**Issue by X901** [T-Pham/UITextField-Navigation#3]
The is one issue
if there is textfield under keyboard and I click Next button it will go to the next textfield
but i can't see thing because the textfield is under keyboard !!

**Comment by T-Pham** [comment]
Hey @X901, thanks for reporting the issue.

Ensuring a textfield's visibility when it is focused is out of the scope of this project (at least for now).
There are various ways to achieve that such as wrapping the view into a scroll view and adjust the scroll view's content inset and/or content offset when a textfield gets focused. I believe there are some libraries which help with that too.
