### ISSUE TITLE
Proper usage when form contains textfields and textviews

### ISSUE THREAD

**Issue by VitaliyR** [T-Pham/UITextField-Navigation#6]
Hi!

Thanks for the awesome pod, works flawlessly. 

The only question I have is how to use it within a form which contains textview - how to map in proper way **nextTextField**?

Thanks!

**Comment by T-Pham** [comment]
@VitaliyR: thanks for using the pod. Linking to UITextView is currently not supported. I wanted to add that feature but couldn't have time to work on it.

**Comment by T-Pham** [comment]
@VitaliyR: I am working on it. A working, but not finalized, version can be found on `support_uitextview` branch.

**Comment by VitaliyR** [comment]
@T-Pham thanks again, will give it a try 👍

**Comment by T-Pham** [comment]
v3.0.0 includes support for `UITextView` besides `UITextField`.
