### ISSUE TITLE
Storyboard Connection Inspector - Sent Actions panel is missing

### ISSUE THREAD

**Issue by VitaliyR** [T-Pham/UITextField-Navigation#7]
Hello!

I'm trying to connect one `UITextField` to another via Storyboard _Connection Inspector_ and it just not allowing me to do so.

Either in the code:

```swift
let firstField = UITextField()
let anotherField = UITextField()

firstField.nextNavigationField = anotherField
firstField.nextNavigationField == nil // true
```

But I still can connect UITextField.nextNavigationField to UITextView. And can't do vice versa.

Have you noticed this, or it happens only to me?

**Comment by VitaliyR** [comment]
Weird thing, removed directory containing the plugin, updated pods repos, installed it again, made a clean build - and everything works again.

But I have one more question:

Because you extending `UITextField` with your custom protocol, it breaks **Storyboard Connection Inspector** - _Sent Actions_ panel is missing. 

Every time I need to connect some actions from the storyboard, I need to comment it out. 

Maybe there are ways to refactor the plugin, so it will not break that stuff?

**Comment by T-Pham** [comment]
Thanks for your feedback @VitaliyR.

Confirm that the Storyboard Connection Inspector issue is happening. Since I will probably not have time to look into a workaround soon, let's hope next Xcode releases will fix that.

**Comment by VitaliyR** [comment]
@T-Pham Maybe it could be considered to refactor the way this library works? I mean, right now the magic is done via `extension` native classes, but what if we could create just a base classes for it? And if people wants to do something on top of it, they would subclass that base classes, not just regular `UITextField`?

Because, as far as I saw, Apple don't chase this bug :(

**Comment by T-Pham** [comment]
I actually wanted to avoid the subclass approach because by creating a textfield subclass for this navigation feature, we may prevent the users of this library from using it together with other textfield libraries which also choose the subclass approach.

**Comment by VitaliyR** [comment]
@T-Pham okay, then we can try to inline that protocol stuff you are extending `UITextField` with.
I found only 2 occurences: `extension UITextField: NavigationField {` and `extension UITextField: NavigationFieldInternal`.

What do you think about it? 

Yes, it will cause code duplicate, but it will fix this bug.

**Comment by T-Pham** [comment]
I am thinking how we declare the IBOutlet nextNavigationField property to get it worked with both UITextField and UITextView and not with other UIControl when not using protocol.

**Comment by T-Pham** [comment]
Just opened a Code-Level Support ticket to Apple regarding this issue. Let's wait for their response.

**Comment by VitaliyR** [comment]
@T-Pham great news, thank! But, anyway, as far as I know, Apple isn't rushing on this one - it is a really old bug (I have found topics dated from 2014, or maybe even earlier :(

**Comment by T-Pham** [comment]
@VitaliyR this issue has been fixed on Xcode 9.

**Comment by VitaliyR** [comment]
@T-Pham thanks, mate, didn't notice it. It took few years to fix this bug :)
