### ISSUE TITLE
Next navigation field not showing in Storyboard if TextfieldNavigation is installed via carthage

### ISSUE THREAD

**Issue by nikhilpandey4** [T-Pham/UITextField-Navigation#9]
Hi
Next navigation field is unavailable in storyboard and is available only in code if UITextfield_Navigation is installed via Carthage but available in storyboard and user can connect visually two text fields  if UITextfield_Navigation is installed via cocoa pods.

**Comment by nikhilpandey4** [comment]
I meant unavailable and not unable

**Comment by nikhilpandey4** [comment]
Hi,
After installing via carthage if one makes a workspace and puts his/her own project along with the 

> **UITextField-Navigation.xcodeproj**
found in the checkout section of the Carthage folder one can access it in storyboard just like cocoa pods.

**Comment by T-Pham** [comment]
Wow, thanks for sharing that @nikhilpandey4.

**Comment by nikhilpandey4** [comment]
Sure and this is the way one can access properties of all such frameworks installed via carthage. In fact you need to link your frameworks and also put the .xcodeproj in a workspace created by you along with your project, this is what even cocoa pods do along with creating metadata. This way your projects will have acres to frameworks and will not have metadata load created by cocoa pods.
